// DO NOT EDIT THIS FILE.
// This file is written automatically by the script generate-action-classes-macro.sh
// and is triggered by an Xcode “Run Script” build phase or from the Makefile.
#define ACTION_CLASSES \
        @"RightClickAction", \
        @"MoveAction", \
        @"KeyDownAction", \
        @"KeyPressAction", \
        @"TripleclickAction", \
        @"KeyUpAction", \
        @"ClickAction", \
        @"DragDownAction", \
        @"WaitAction", \
        @"PrintAction", \
        @"DragUpAction", \
        @"ColorPickerAction", \
        @"DoubleclickAction", \
        @"TypeAction", \
        nil
